name: hotel_booking_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^9.3.0+1
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  hydrated_bloc: ^10.0.0
  internet_connection_checker: ^3.0.1
  intl: any
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  skeletonizer: ^2.1.0+1

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/profile-svgrepo-com.svg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
