name: Flutter Release Builds

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLUTTER_VERSION: ${{ vars.FLUTTER_VERSION }}

jobs:
  analyze_and_format:
    name: "ðŸ§¹ Analyze & Format"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env File (for analyzer)
        run: echo "URL=" > .env

      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run analyzer (fail if any issue)
        run: dart analyze . || { echo "âŒ Flutter analyze failed"; exit 1; }

      - name: Check formatting (fail if changed)
        run: |
          dart format --set-exit-if-changed . || { echo "âŒ Code not formatted properly"; exit 1; }

  test:
    name: "ðŸ§ª Run Tests"
    runs-on: ubuntu-latest
    needs: analyze_and_format

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Check .env File Content
        run: cat .env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Check Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Run tests (fail on any failure)
        run: |
          flutter test --coverage || { echo "âŒ Tests failed"; exit 1; }

  build_android:
    needs: test
    name: "ðŸ Build Android Release Artifacts"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Check .env File Content
        run: cat .env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Check Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Build Play Store App Bundle (.aab)
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
