name: Upload Demo Video and Screenshot

on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - main
      - master

jobs:
  capture-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Demo Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: Demo-screenshots
          path: assets/screenshots/
          if-no-files-found: ignore


